const constants = {
  PASS_NFT_CONTRACT_ADDRESS:
    process.env.MODE === "prod"
      ? process.env.NEXT_PUBLIC_PROD_PASS_NFT_CONTRACT_ADDRESS
      : process.env.NEXT_PUBLIC_DEV_PASS_NFT_CONTRACT_ADDRESS,
  MINTER_NFT_CONTRACT_ADDRESS:
    process.env.MODE === "prod"
      ? process.env.NEXT_PUBLIC_PROD_MINTER_NFT_CONTRACT_ADDRESS
      : process.env.NEXT_PUBLIC_DEV_MINTER_NFT_CONTRACT_ADDRESS,

  SEPOLIA_NETWORK_ID: "11155111",
  LOCAL_NETWORK_ID: "31337",

  MM_ERROR_CODE__USER_REJECT_REQUEST: 4001
};
export default constants;
